name: Deploy on Cloudflare

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      commit:
        required: false
        type: string
      comment:
        required: false
        type: boolean
      artifact_name:
        required: false
        type: string
        default: frontend

jobs:
  cf-pages:
    name: CloudFlare Pages 📃
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.branch == 'main' }}
      url: ${{ steps.cf.outputs.deployment-url }}
    outputs:
      url: ${{ steps.cf.outputs.deployment-url }}

    steps:
      - name: Download workflow artifact ⬇️
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: dist

      - name: Publish to Cloudflare Pages 📃
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        id: cf
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=fappen --branch=${{ inputs.branch }}

  compose-comment:
    name: Create comment
    uses: GrantBirki/comment@v2.1.1
      with:
        body: |
          This is a multi-line test comment

          - With GitHub **Markdown** ✨
          - Cool!
          - ${{ inputs.branch }}
          - ${{ inputs.commit }}
          - ${{ needs.cf-pages.outputs.url }}
          - ${{ inputs.comment }}
        reactions: '+1'
    # Always run so the comment is composed for the workflow summary
    if: ${{ always() }}
    needs:
      - cf-pages
